# Generated by Django 3.2 on 2021-04-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0002_auto_20210423_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.TextField(default='rub', verbose_name='Валюта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(unique=True, verbose_name='Сылка'),
        ),
    ]
