# Generated by Django 3.2 on 2021-04-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0006_alter_product_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=300, unique=True, verbose_name='Сылка'),
        ),
    ]
